version: '2'
services:
  roscore:
    image: autovr
    command: roscore
    ports:
      - 11311:11311
    environment:
      - "ROS_HOSTNAME=roscore"

  player:
    image: autovr
#    command: rosbag play -q --clock /rosbags/2016-05-10-23-52-57.bag
    command: rosbag play -q -l --clock /rosbags/2016-05-10-23-52-57.bag
    volumes:
      - ${ROSBAGDIR}:/rosbags
    environment:
      - "ROS_HOSTNAME=player"
      - "ROS_MASTER_URI=http://roscore:11311"
    depends_on:
      - roscore
#    restart: always

  websocket:
    image: autovr
    command: roslaunch rosbridge_server rosbridge_websocket.launch
    ports:
      - 9090:9090
    environment:
      - "ROS_HOSTNAME=websocket"
      - "ROS_MASTER_URI=http://roscore:11311"
    depends_on:
      - roscore
    restart: always

  tf2:
    image: autovr
    command: rosrun tf2_web_republisher tf2_web_republisher
    environment:
      - "ROS_HOSTNAME=tf2"
      - "ROS_MASTER_URI=http://roscore:11311"
    depends_on:
      - roscore


