FROM ros:indigo

RUN apt-get update && apt-get install -y \
    python-twisted \
    ros-indigo-rosbridge-server \
    ros-indigo-tf2-web-republisher \
    && rm -rf /var/lib/apt/lists/

# add launchfile for starting rosbag and tf2_web_republisher together
# this is necessary to make tf2_web_republisher restart when log player exits
ADD LogPlayback.launch LogPlayback.launch

ADD entrypoint.sh entrypoint.sh
RUN perl -p -i -e "s/\r//g" entrypoint.sh
#ENTRYPOINT ["/bin/bash"]
 ENTRYPOINT [ "/entrypoint.sh"]
 CMD ["/bin/bash"]
