FROM ros:indigo

# place here your application's setup specifics
# ADD logfile.bag logfile.bag 

RUN apt-get update && apt-get install -y \
    python-twisted \
    ros-indigo-rosbridge-server \
    ros-indigo-tf2-web-republisher \
    && rm -rf /var/lib/apt/lists/ 

ADD entrypoint.sh entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh"]
CMD ["/bin/bash"]
